### PR TITLE
Updated qcbm example.

### PR DESCRIPTION
**Pull request by mstechly**
I've added qulacs as a simulator, as it's faster than qiskit.
+ cleaned the structure a little bit.

### CODE REVIEW

**Comment by mstechly** [comment]
@1ethanhansen – once this is merged do you want me to update the docs with new format (for consistency sake) or is it something you'd rather do yourself?

**Review by martamau — APPROVED** [review]

**Review by 1ethanhansen — APPROVED** [review]
lgtm! I just tried it start to finish and I got a weird error in the plotting the first time, but I think that was due to me tweaking the GUI settings :)

**Comment by 1ethanhansen** [comment]
@mstechly if you could update the docs that would be great! maybe tag me in the PR so I can take a second pass at it?

**Comment by mstechly** [comment]
Sure, thanks @1ethanhansen !

**Pull request merged**
